### ISSUE TITLE
Preanalysis Task fails

### ISSUE THREAD

**Issue by eightBEC** [IBM/powerai-vision-object-detection#26] opened 2018-05-15 12:05 UTC
After uploading the coke_bottles_exported.zip and creating a new Object Detection DL Task in the Web Tooling of IBM PowerAI Vision the Build Model Task fails with the error "Preanalysis task failed".

This seems to be an issue as this happens withe the zip that's contained in this repo as well as files labeled by myself.

**Comment by markstur** [comment] 2018-05-17 17:13
trying to reproduce now

**Comment by markstur** [comment] 2018-05-17 18:49
I was able to train and test with the exported zip today. I'm going to close this as cannot reproduce. Will be doing more end-to-end testing later.

@eightBEC do you still have this problem?  Any additional info. Are you on SuperVessel. Not sure why our results are different.  Hoping it was a temporary issue and is really fixed.

**Closed by markstur** 2018-05-17 18:49 UTC
